---

# Step 1: Install Fail2Ban
- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present
  become: true

# Step 2: Ensure Fail2Ban directory exists
- name: Ensure Fail2Ban configuration directory exists
  file:
    path: /etc/fail2ban
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

# Step 3: Configure Fail2Ban
- name: Deploy Fail2Ban configuration for SSH
  template:
    src: ssh.local.j2
    dest: /etc/fail2ban/jail.d/ssh.local
    owner: root
    group: root
    mode: 0644
  notify: Restart Fail2Ban
  become: true

# Step 4: Enable and start Fail2Ban
- name: Enable and start Fail2Ban
  service:
    name: fail2ban
    state: started
    enabled: true
  become: true
